### ISSUE TITLE
problem when compile

### ISSUE THREAD

**Issue by fwzhuangCg** [fanxiaochen/Point-Set-Registration#1]
The methods in CDBbase cannot use the  protected variables in class registration:
    protected:
        TMatrixD            _model;
        TMatrixD            _data;
        size_t              _M;
        size_t              _N;
        RegType             _type;
        bool                _vision;
In file included from /home/kevin/work/Point-Set-Registration-master/include/core/cpd_rigid.hpp:34:0,
                 from /home/kevin/work/Point-Set-Registration-master/src/test.cpp:5:
/home/kevin/work/Point-Set-Registration-master/include/core/cpd_base.hpp: In member function ‘void cpd::CPDBase<T, D>::updateModel()’:
/home/kevin/work/Point-Set-Registration-master/include/core/cpd_base.hpp:162:9: error: ‘_model’ was not declared in this scope
         _model = _T;
         ^
/home/kevin/work/Point-Set-Registration-master/include/core/cpd_base.hpp: In member function ‘void cpd::CPDBase<T, D>::initTransform()’:
/home/kevin/work/Point-Set-Registration-master/include/core/cpd_base.hpp:168:14: error: ‘_model’ was not declared in this scope
         _T = _model;
What's wrong?

**Comment by fanxiaochen** [comment]
Actually I haven't tested my cpd code on linux platform. At least, it could work on windows. The compile error here seems to be gcc's different supporting for c++ standard  from vc compiler. I think you could change the '_model' to be public, which it's ugly but may be work. Anyway, I'll try it on linux and make sure there's no big problem for both platform.

**Comment by fanxiaochen** [comment]
Now it could work on linux. Fix template supporting problem between different compilers.
